# Generated by Django 4.1.2 on 2022-10-16 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('po', models.BigIntegerField()),
                ('permitNumber', models.CharField(blank=True, max_length=200)),
                ('bidNumber', models.DecimalField(decimal_places=2, max_digits=50)),
                ('status', models.CharField(choices=[('B', 'Bid'), ('A', 'Accepted'), ('S', 'Started'), ('C', 'Closed')], default='B', max_length=3)),
                ('contractCompleteDate', models.DateField()),
                ('projectedStartDate', models.DateField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.address')),
            ],
        ),
    ]
